name: Test Secrets

on:
  push:
    branches:
      - main

jobs:
  test_secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Secret Values
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        echo "SSH Private Key: $SSH_PRIVATE_KEY"
        echo "SSH Public Key: $SSH_PUBLIC_KEY"
        echo "Server IP: $SERVER_IP"
